name: "Upload scan results"
on: 
    workflow_dispatch:
jobs:
    sarif:
        runs-on: ubuntu-latest
        permissions:
          # required for all workflows
          security-events: write
          # only required for workflows in private repositories
          actions: read
          contents: read
        steps:
          - uses: actions/checkout@v4
          - name: Test
            run: ls -la
          - name: Upload report
            uses: github/codeql-action/upload-sarif@v3
            with:
              sarif_file: report.sarif
              category: my-analysis-tool
